"""Add makemkv_key to settings

Revision ID: fa83c3a48f73
Revises: 896b94254e69
Create Date: 2026-06-01 10:19:54.573098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa83c3a48f73'
down_revision: Union[str, Sequence[str], None] = '896b94254e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('makemkv_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'makemkv_key')
    # ### end Alembic commands ###
